/**
 * export/rawDataSheet.ts — "Constants & Provenance" sheet builder for the Excel audit model.
 * Extracted from ExcelExport.tsx.
 */

import type { ExcelExportData } from '../ExcelExport';

export function buildProvenance(d: ExcelExportData): any[][] {
  return [
    ["OPENPLANET — Scientific Constants & Data Provenance", "", "", ""],
    ["For academic review, investor due diligence, and model verification.", "", "", ""],
    ["", "", "", ""],
    ["━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━", "", "", ""],
    ["PEER-REVIEWED CONSTANTS", "", "", ""],
    ["━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━", "", "", ""],
    ["Constant", "Value", "Description", "Full Citation"],
    ["β (Gasparrini Beta)",    "0.0801",  "Log-linear heat-mortality coefficient",       "Gasparrini A. et al. (2017). Lancet Planetary Health."],
    ["T_optimal (Burke)",      "13°C",    "Global GDP-optimal temperature",              "Burke M. et al. (2018). Nature."],
    ["ILO Workforce Fraction", "0.40",    "Fraction of workforce in heat-exposed sectors","ILO (2019). Working on a Warmer Planet."],
    ["ILO Productivity Loss",  "0.20",    "Weighted productivity loss per HW day",       "ILO (2019) ibid."],
    ["Canopy Coefficient",     "1.2°C",   "Cooling per 100% canopy coverage",            "Bowler D.E. et al. (2010). Landscape and Urban Planning."],
    ["Albedo Coefficient",     "0.8°C",   "Cooling per 100% reflective roof coverage",   "Santamouris M. (2015). Energy and Buildings."],
    ["WBT Physiological Cap",  "35.0°C",  "Human thermoregulation absolute limit",       "Sherwood S.C. & Huber M. (2010). PNAS."],
    ["Death Rate CI",          "±15%",    "Beta coefficient uncertainty range",          "Gasparrini (2017) ibid."],
    ["Economic CI",            "±8%",     "GDP loss model uncertainty range",            "Burke (2018) ibid."],
    ["HW Reduction Rate",      "3.5 d/°C","Heatwave days reduced per °C cooling",        "Derived from Bowler (2010) + Santamouris (2015)"],
    ["Severity Reduction",     "8%/°C",   "Mortality/loss severity reduction per °C",    "Derived from mitigation literature composite"],
    ["", "", "", ""],
    ["━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━", "", "", ""],
    ["STULL (2011) WET-BULB FORMULA", "", "", ""],
    ["━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━", "", "", ""],
    ["WBT = T·atan(0.151977·√(RH+8.313659)) + atan(T+RH) − atan(RH−1.676331) + 0.00391838·RH^1.5·atan(0.023101·RH) − 4.686035", "", "", ""],
    ["Where: T = peak temperature (°C), RH = relative humidity (%)", "", "", ""],
    ["Accuracy: ±0.65°C. Capped at 35°C per Sherwood & Huber (2010).", "", "", ""],
    ["", "", "", ""],
    ["━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━", "", "", ""],
    ["DATA SOURCES & LIVE API CALLS", "", "", ""],
    ["━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━", "", "", ""],
    ["Dataset", "Source", "API Endpoint", "What It Provides"],
    ["ERA5 Historical Baseline", "Open-Meteo / ECMWF Copernicus","archive-api.open-meteo.com/v1/archive",  "1991-2020 daily Tmax — P95 threshold calculation"],
    ["CMIP6 Projections",        "Open-Meteo Climate API",        "climate-api.open-meteo.com/v1/climate",  "2015-2050: MRI-AGCM3-2-S, MPI-ESM1-2-XR ensemble (horizon capped at 2050)"],
    ["Socioeconomic Data",       "OpenPlanet Verified City Vault","city_vault.json (hardcoded)",             "UN/World Bank/Census 2023-2024 · 59+ cities · no dynamic scraping"],
    ["GDP per Capita",           "World Bank / City Vault",        "Verified City Vault (primary)",          "City-vault GDP/capita × metro population × urban productivity ratio"],
    ["Crude Death Rate",         "World Bank API",                 "api.worldbank.org/v2 — SP.DYN.CDRT.IN", "Crude death rate per 1,000 population"],
    ["Urban Share",              "World Bank API",                 "api.worldbank.org/v2 — SP.URB.TOTL.IN.ZS","Urban population % for metro GDP multiplier"],
    ["Age Structure",            "World Bank API",                 "api.worldbank.org/v2 — SP.POP.0014+65UP","Age structure proxy for vulnerability multiplier"],
    ["Healthcare Access",        "World Bank API",                 "api.worldbank.org/v2 — SH.MED.PHYS.ZS", "Physicians per 1,000 — healthcare component of V"],
    ["City Population",          "GeoNames API",                   "api.geonames.org/searchJSON",            "Metro population + country code"],
    ["", "", "", ""],
    ["━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━", "", "", ""],
    ["ADDITIONAL REFERENCES", "", "", ""],
    ["━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━", "", "", ""],
    ["C40 Cities (2021)",         "Nature-Based Solutions for Urban Climate Resilience","C40 Cities Finance Facility","Investment cost estimates for urban cooling programs"],
    ["Levinson R. (2018)",        "Energy savings from cool roofs","Lawrence Berkeley National Laboratory (LBNL)","Cool roof economic cost estimates"],
    ["GBD 2019",                  "Global burden of 87 risk factors","The Lancet","Age-specific vulnerability multipliers"],
    ["UN WUP (2022)",             "World Urbanization Prospects","United Nations DESA","Population age share estimates"],
    ["Hersbach H. et al. (2020)", "The ERA5 global reanalysis","Q. J. R. Meteorol. Soc.","ERA5 dataset description"],
    ["IPCC AR6 WG1 (2021)",       "Climate Change 2021: Physical Science Basis","Cambridge University Press","Regional warming projections Ch.4 + Ch.11"],
    ["", "", "", ""],
    ["━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━", "", "", ""],
    ["LEGAL DISCLAIMER", "", "", ""],
    ["━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━", "", "", ""],
    ["⚠ All outputs are research-grade estimates for analytical and educational purposes only.", "", "", ""],
    ["⚠ Not investment advice. Not a financial instrument. Not a deterministic forecast.", "", "", ""],
    ["⚠ Mortality: ±15% CI from Gasparrini (2017) beta coefficient uncertainty.", "", "", ""],
    ["⚠ Economics: ±8% CI from Burke (2018) model uncertainty.", "", "", ""],
    ["⚠ City GDP is estimated — no API provides direct city-level GDP globally.", "", "", ""],
    ["⚠ Post-2050 values use IPCC AR6 regional deltas, not direct CMIP6 model output.", "", "", ""],
    ["⚠ Adaptation cost estimates are order-of-magnitude from published literature.", "", "", ""],
  ];
}
