/**
 * export/summarySheet.ts — "README" sheet builder for the Excel audit model.
 * Extracted from ExcelExport.tsx.
 */

import type { ExcelExportData } from '../ExcelExport';
import type { DerivedCalc } from './sheetHelpers';

export function buildReadme(d: ExcelExportData, calc: DerivedCalc): any[][] {
  return [
    ["╔══════════════════════════════════════════════════════════════════════╗"],
    ["║        OPENPLANET RISK INTELLIGENCE — FINANCIAL AUDIT MODEL          ║"],
    ["║                    Peer-Reviewed Climate Economics                   ║"],
    ["╚══════════════════════════════════════════════════════════════════════╝"],
    [""],
    ["CITY",         d.city_name],
    ["COORDINATES",  `${(d.lat||0).toFixed(4)}°N, ${(d.lng||0).toFixed(4)}°E`],
    ["SCENARIO",     d.ssp],
    ["TARGET YEAR",  d.target_year],
    ["GENERATED",    new Date().toLocaleString()],
    [""],
    ["━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"],
    ["HOW TO USE THIS MODEL"],
    ["━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"],
    [""],
    ["STEP 1", "Go to the 'Control Panel' tab"],
    ["STEP 2", "Find the section marked '⚡ EDITABLE INPUTS — Change these numbers'"],
    ["STEP 3", "Edit any value in Column B (rows 10–19)"],
    ["STEP 4", "ALL outputs on this sheet AND Core Engine recalculate instantly"],
    ["STEP 5", "View full formula derivations on the 'Core Engine' tab"],
    [""],
    ["━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"],
    ["SHEET GUIDE"],
    ["━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"],
    [""],
    ["README",                  "This sheet — model guide and city metadata"],
    ["Control Panel",           "Edit inputs here → all outputs auto-recalculate"],
    ["Core Engine",             "Full peer-reviewed math — Gasparrini + Burke + Stull"],
    ["Constants & Provenance",  "Scientific constants, API sources, full citations"],
    [""],
    ["━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"],
    ["MODELS USED"],
    ["━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"],
    [""],
    ["MORTALITY",   "Gasparrini et al. (2017), Lancet Planetary Health — β = 0.0801"],
    ["ECONOMICS",   "Burke et al. (2018), Nature — T_optimal = 13°C"],
    ["LABOR",       "ILO (2019) — 40% workforce × 20% productivity loss per HW day"],
    ["WET-BULB",    "Stull (2011) — empirical formula, capped at 35°C (Sherwood & Huber 2010)"],
    ["CANOPY",      "Bowler et al. (2010) — 1.2°C cooling per 100% coverage"],
    ["COOL ROOFS",  "Santamouris (2015) — 0.8°C cooling per 100% coverage"],
    ["CLIMATE",     `CMIP6 via Open-Meteo — ${d.cmip6_source}`],
    [""],
    ["━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"],
    ["KEY RESULTS SUMMARY"],
    ["━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"],
    [""],
    ["Attributable Deaths (baseline)",  calc.attributable_deaths.toLocaleString(),  "lives/yr",  "Gasparrini (2017)"],
    ["Economic Loss (baseline)",         `$${(calc.economic_decay_usd/1e9).toFixed(2)}B`, "USD/yr",    "Burke (2018) + ILO (2019)"],
    ["Peak Temperature",                 `${calc.peak_tx5d_c.toFixed(1)}°C`,         "",          "Open-Meteo CMIP6"],
    ["Annual Heatwave Days",             `${calc.heatwave_days.toFixed(0)} days`,     "",          "CMIP6 Ensemble"],
    ["Wet-Bulb Temperature",             `${calc.wbt.toFixed(1)}°C`,                 "",          "Stull (2011)"],
    [""],
    ["━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"],
    ["LEGAL DISCLAIMER"],
    ["━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"],
    [""],
    ["⚠ All outputs are research-grade estimates for analytical and educational purposes only."],
    ["⚠ Not investment advice. Not a financial instrument. Not a forecast."],
    ["⚠ Mortality estimates carry ±15% uncertainty (Gasparrini 2017 beta coefficient)."],
    ["⚠ Economic estimates carry ±8% uncertainty (Burke 2018 model)."],
    ["⚠ City GDP estimated from World Bank national data × urban productivity ratio."],
    ["⚠ Post-2050 projections use IPCC AR6 regional delta rates, not direct CMIP6 output."],
  ];
}
