import Link from 'next/link';

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#020617] text-slate-300 font-sans selection:bg-white/10">
      
      {/* MINIMAL HEADER */}

      {/* CONTENT DOCUMENT */}
      <main className="max-w-3xl mx-auto px-6 py-24">
        <div className="mb-16">
          <h1 className="text-3xl md:text-5xl font-bold text-white tracking-tight mb-4">Terms of Service</h1>
          <p className="text-slate-500 font-mono text-xs uppercase tracking-widest">Effective Date: March 2026 | Document Ref: OP-TOS-01</p>
        </div>

        <div className="space-y-12 text-sm md:text-base font-light leading-relaxed">
          
          <section>
            <h2 className="text-white font-medium text-lg mb-4 flex items-center gap-3">
              <span className="text-slate-600 font-mono text-sm">1.0</span> Nature of the Analytics Service
            </h2>
            <p className="text-slate-400">
              The platform provides advanced spatial computing, probabilistic forecasting, and environmental risk analytics. The models, metrics, and projections generated by the engine are based on localized data inputs and international scientific consensus frameworks. By utilizing the service, the user acknowledges that environmental forecasting is inherently probabilistic. The data represents simulated scenarios and potential risk exposures, not guaranteed future events.
            </p>
          </section>

          <section>
            <h2 className="text-white font-medium text-lg mb-4 flex items-center gap-3">
              <span className="text-slate-600 font-mono text-sm">2.0</span> Limitation of Liability and Use of Data
            </h2>
            <p className="text-slate-400 mb-4">All projections, financial exposure models, and demographic risk assessments are provided strictly for informational, research, and strategic planning purposes.</p>
            <ul className="space-y-4 border-l border-white/10 pl-6 ml-2">
              <li className="text-slate-400"><strong className="text-white font-medium">No Financial Advice:</strong> The analytics do not constitute financial, investment, or legal advice. Investors, asset managers, and corporate entities must conduct independent due diligence before making capital allocations.</li>
              <li className="text-slate-400"><strong className="text-white font-medium">No Life-Safety Reliance:</strong> The platform is not a real-time emergency alert system and must not be used as the sole basis for immediate life-safety or disaster response operations.</li>
              <li className="text-slate-400"><strong className="text-white font-medium">Absolute Shield:</strong> Under no circumstances shall the provider, its engineers, or its investors be held liable for any direct, indirect, capital, or operational losses incurred as a result of decisions made based on the platform’s predictive outputs.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-white font-medium text-lg mb-4 flex items-center gap-3">
              <span className="text-slate-600 font-mono text-sm">3.0</span> Data Provenance and Scientific Uncertainty
            </h2>
            <p className="text-slate-400">
              The analytical engine aggregates data from global meteorological institutions, international health organizations, and aerospace agencies. While the provider utilizes rigorous mathematical modeling (including multi-draw simulations) to ensure high-fidelity outputs, the provider does not warrant the absolute accuracy of underlying third-party datasets. The user accepts that macro-environmental models are subject to scientific uncertainties and evolving methodological standards.
            </p>
          </section>

          <section>
            <h2 className="text-white font-medium text-lg mb-4 flex items-center gap-3">
              <span className="text-slate-600 font-mono text-sm">4.0</span> Intellectual Property and Proprietary Rights
            </h2>
            <p className="text-slate-400">
              The proprietary algorithms, spatial indexing methodologies, user interface design, and compiled analytical frameworks are the exclusive intellectual property of the provider. Users are granted a limited, non-exclusive license to utilize the engine for internal strategic assessments. Reverse engineering, unauthorized scraping, or commercial resale of the platform’s direct outputs without an enterprise licensing agreement is strictly prohibited.
            </p>
          </section>

          <section>
            <h2 className="text-white font-medium text-lg mb-4 flex items-center gap-3">
              <span className="text-slate-600 font-mono text-sm">5.0</span> System Integrity and Acceptable Use
            </h2>
            <p className="text-slate-400">
              The user agrees to interact with the system via standard interface protocols. Any attempt to artificially inflate simulation limits, bypass authentication gateways, or inject malicious geographic queries designed to disrupt the spatial computing engine will result in immediate termination of access.
            </p>
          </section>

        </div>
      </main>
    </div>
  );
}