import os
import logging
import json
from groq import AsyncGroq

logger = logging.getLogger(__name__)

async def generate_strategic_analysis(
    city: str, ssp: str, year: str, canopy: int, coolRoof: int,
    calc_temp: float, calc_heatwaves: int, calc_deaths: int, calc_loss_usd: float
) -> dict:
    """
    STRICT GROUNDED LLM CALL: Forces the AI to write its strategic analysis
    based exclusively on the numbers generated by the Python physics engine.
    """
    client = AsyncGroq(api_key=os.environ.get("GROQ_API_KEY"))

    # Format the money string exactly like the frontend
    if calc_loss_usd > 1000000000:
        loss_str = f"${round(calc_loss_usd / 1000000000, 2)}B"
    else:
        loss_str = f"${round(calc_loss_usd / 1000000, 1)}M"

    prompt = f"""
    You are an institutional Climate Risk Analyst. You are writing an empirical brief for {city} in the year {year} under the {ssp} scenario.
    
    CRITICAL ENGINE DATA - YOU MUST USE THESE EXACT NUMBERS IN YOUR ANALYSIS:
    - Peak Heatwave Temperature: {calc_temp}°C
    - Extreme Heatwave Days per Year: {calc_heatwaves} days
    - Attributable Excess Deaths: {calc_deaths} lives
    - Direct Economic Capital Loss: {loss_str} USD
    - Mitigation Applied: +{canopy}% canopy cover, +{coolRoof}% cool roofs.

    STRICT RULES:
    1. DO NOT hallucinate national GDP percentages. Use the EXACT {loss_str} figure for the Economic analysis.
    2. DO NOT hallucinate percentages for sea level rise. Sea level is measured in meters. Focus on heat stress and localized urban infrastructure.
    3. Use the EXACT {calc_deaths} figure for the Mortality analysis.

    Respond with a raw JSON object containing exactly 4 keys: "mortality", "economic", "infrastructure", "mitigation".
    The value for each key MUST follow this exact format:
    **CAUSE:** [1 concise sentence on the localized climate driver]. **EFFECT:** [1 concise sentence incorporating the exact engine data provided]. **SOLUTION:** [1 concise sentence on an adaptation strategy].
    """

    try:
        completion = await client.chat.completions.create(
            model="llama-3.1-8b-instant",  # <-- NEW LIVE MODEL
            messages=[{"role": "user", "content": prompt}],
            temperature=0.2,
            response_format={"type": "json_object"}
        )
        
        raw_response = completion.choices[0].message.content
        return json.loads(raw_response)
        
    except Exception as e:
        logger.error(f"Grounded AI Analysis failed: {e}")
        return {
            "mortality": f"**CAUSE:** AI Offline. **EFFECT:** {e} **SOLUTION:** Check Groq API.",
            "economic": "**CAUSE:** N/A **EFFECT:** N/A **SOLUTION:** N/A",
            "infrastructure": "**CAUSE:** N/A **EFFECT:** N/A **SOLUTION:** N/A",
            "mitigation": "**CAUSE:** N/A **EFFECT:** N/A **SOLUTION:** N/A"
        }