import os
import logging
import json
from groq import AsyncGroq

logger = logging.getLogger(__name__)

async def generate_strategic_analysis(
    city: str, ssp: str, year: str, canopy: int, coolRoof: int,
    calc_temp: float, calc_heatwaves: int, calc_deaths: int, calc_loss_usd: float
) -> dict:
    """
    STRICT GROUNDED LLM CALL: Forces the AI to write its strategic analysis
    based exclusively on the numbers generated by the Python physics engine.
    """
    # 1. API Key Safety Check
    api_key = os.environ.get("GROQ_API_KEY")
    if not api_key:
        logger.error("GROQ_API_KEY is missing from environment variables.")
        return _fallback_error("API Key Missing", "Check Hugging Face Secrets.")

    client = AsyncGroq(api_key=api_key)

    # 2. Format the money string exactly like the frontend
    if calc_loss_usd > 1000000000:
        loss_str = f"${round(calc_loss_usd / 1000000000, 2)}B"
    else:
        loss_str = f"${round(calc_loss_usd / 1000000, 1)}M"

    prompt = f"""
    You are an institutional Climate Risk Analyst. You are writing an empirical brief for {city} in the year {year} under the {ssp} scenario.
    
    CRITICAL ENGINE DATA - YOU MUST USE THESE EXACT NUMBERS IN YOUR ANALYSIS:
    - Peak Heatwave Temperature: {calc_temp}°C
    - Extreme Heatwave Days per Year: {calc_heatwaves} days
    - Attributable Excess Deaths: {calc_deaths} lives
    - Direct Economic Capital Loss: {loss_str} USD
    - Mitigation Applied: +{canopy}% canopy cover, +{coolRoof}% cool roofs.

    STRICT RULES:
    1. DO NOT hallucinate national GDP percentages. Use the EXACT {loss_str} figure for the Economic analysis.
    2. DO NOT hallucinate percentages for sea level rise. Focus strictly on heat stress, thermal expansion, and localized urban infrastructure.
    3. Use the EXACT {calc_deaths} figure for the Mortality analysis.
    4. Use the EXACT {calc_temp}°C and {calc_heatwaves} days for the Mitigation analysis.

    You MUST respond with a valid JSON object. Do not include any text outside the JSON.
    The JSON must have exactly these 4 keys: "mortality", "economic", "infrastructure", "mitigation".
    The value for each key MUST follow this exact string format:
    "**CAUSE:** [1 concise sentence]. **EFFECT:** [1 concise sentence using the EXACT engine data]. **SOLUTION:** [1 concise sentence]."
    """

    try:
        completion = await client.chat.completions.create(
            model="llama-3.1-8b-instant",
            messages=[{"role": "user", "content": prompt}],
            temperature=0.1,  # EXTREMELY low temp forces strict adherence to the math
            response_format={"type": "json_object"}
        )
        
        raw_response = completion.choices[0].message.content
        
        # 3. BULLETPROOF JSON CLEANER
        # Strips out any markdown backticks the AI accidentally includes
        clean_response = raw_response.strip()
        if clean_response.startswith("```json"):
            clean_response = clean_response[7:-3].strip()
        elif clean_response.startswith("```"):
            clean_response = clean_response[3:-3].strip()

        return json.loads(clean_response)
        
    except Exception as e:
        logger.error(f"Grounded AI Analysis failed: {e}")
        return _fallback_error("AI Generation Failed", str(e))

def _fallback_error(cause: str, effect: str) -> dict:
    """Helper function to guarantee the frontend never receives a broken dictionary structure."""
    return {
        "mortality": f"**CAUSE:** {cause} **EFFECT:** {effect} **SOLUTION:** Check logs.",
        "economic": "**CAUSE:** N/A **EFFECT:** N/A **SOLUTION:** N/A",
        "infrastructure": "**CAUSE:** N/A **EFFECT:** N/A **SOLUTION:** N/A",
        "mitigation": "**CAUSE:** N/A **EFFECT:** N/A **SOLUTION:** N/A"
    }

# --- ADDED TO THE BOTTOM OF llm_service.py ---

async def generate_strategic_analysis_raw(prompt: str) -> str:
    """
    Handles direct, raw prompts for the Research and Compare AI Auditor.
    """
    try:
        # Initialize Groq client using the globally imported os and AsyncGroq
        client = AsyncGroq(api_key=os.environ.get("GROQ_API_KEY"))
        
        response = await client.chat.completions.create(
            model="llama-3.1-8b-instant", # Fast and highly accurate model
            messages=[
                {
                    "role": "system", 
                    "content": "You are a senior climate risk auditor. Explain the physics and economics of the provided data concisely. Do not hallucinate. Keep it under 3-4 sentences."
                },
                {
                    "role": "user", 
                    "content": prompt
                }
            ],
            temperature=0.3,
            max_tokens=250
        )
        return response.choices[0].message.content.strip()
        
    except Exception as e:
        logger.error(f"Groq Raw API Error: {str(e)}")
        return "Expert AI reasoning is currently unavailable due to network processing load. Please refer to the raw telemetry metrics above."